name: Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: ensure your repo has a top-level README.md with Spaces metadata
      - name: Ensure README has Spaces metadata
        run: |
          if ! grep -q "sdk: gradio" README.md; then
            echo "Missing Spaces metadata. Please add it as shown in the instructions."
          fi

      - name: Publish to Hugging Face Hub (Space)
        uses: huggingface/action-publish-huggingface-hub@v1
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        with:
          repo-type: space
          # Set YOUR username_or_org and space name:
          repo: janaka2/RAG_Powerd_Chat_Bot
          # Pick the SDK you use
          space-sdk: gradio
          # Optionally set the hardware (see HF docs for options)
          # space-hardware: cpu-basic
          # Optional: which branch of the Space to push to
          # branch: main