name: Sync to Hugging Face Space

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      HF_USERNAME: janaka2                 # exact owner
      HF_SPACE:    RAG_Powerd_Chat_Bot     # exact space slug

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Sanity check files
        run: |
          ls -la
          test -f app.py || { echo "::error::app.py missing at repo root"; exit 1; }
          test -f README.md || { echo "::warning::README.md missing"; }

      - name: Git identity & LFS
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git lfs install

      - name: Install HF CLI
        run: pip install --upgrade "huggingface_hub>=0.24.0"

      - name: Verify token & login via credential helper
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "::error::HF_TOKEN secret is missing"; exit 1
          fi
          # Verify token is valid
          huggingface-cli whoami --token "$HF_TOKEN"
          # Add token to git credential helper (no token in URL)
          huggingface-cli login --token "$HF_TOKEN" --add-to-git-credential

      - name: Push to HF Space (HEAD -> main) without embedding token
        run: |
          set -e
          REMOTE="https://huggingface.co/spaces/${HF_USERNAME}/${HF_SPACE}"
          git remote add hf "$REMOTE" || git remote set-url hf "$REMOTE"
          git push --force hf HEAD:main
