name: Sync to Hugging Face Space

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      HF_USER: janaka2
      HF_SPACE: RAG_Powerd_Chat_Bot

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Show repo tree (debug)
        run: |
          echo "== Top-level files =="
          ls -la
          echo "== Git status =="
          git status
          echo "== Expect app.py at repo root =="
          test -f app.py && echo "OK: app.py found" || (echo "::error::app.py missing at repo root"; exit 1)

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install huggingface_hub
        run: pip install --upgrade huggingface_hub

      - name: Verify HF token (whoami)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - <<'PY'
from huggingface_hub import whoami
import os, sys
tok=os.environ.get("HF_TOKEN")
if not tok:
    print("HF_TOKEN is missing"); sys.exit(1)
print("whoami:", whoami(tok))
PY

      - name: Ensure Space exists
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - <<'PY'
from huggingface_hub import HfApi
import os
api=HfApi()
user=os.environ["HF_USER"]
space=os.environ["HF_SPACE"]
tok=os.environ["HF_TOKEN"]
api.create_repo(repo_id=f"{user}/{space}", repo_type="space", exist_ok=True, token=tok, space_sdk="gradio")
print(f"ensured https://huggingface.co/spaces/{user}/{space}")
PY

      - name: Install Git LFS
        run: git lfs install

      - name: Push to HF Space (force)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          set -e
          REMOTE="https://${HF_USER}:${HF_TOKEN}@huggingface.co/spaces/${HF_USER}/${HF_SPACE}"
          git remote add hf "$REMOTE" || git remote set-url hf "$REMOTE"
          echo "Pushing HEAD -> main"
          git push --force hf HEAD:main
