name: Sync to Hugging Face Space

on:
  push:
    branches: [ main ]   # change if your default branch is different
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set git identity
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Install Git LFS
        run: |
          git lfs install

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USER:  janaka2                     # <-- set your HF username/org
          HF_SPACE: RAG_Powerd_Chat_Bot         # <-- EXACT space name in the URL
          BRANCH:   main
        run: |
          # Push current branch to the Space's main branch
          git push "https://${HF_USER}:${HF_TOKEN}@huggingface.co/spaces/${HF_USER}/${HF_SPACE}" "${BRANCH}:${BRANCH}"
