name: Sync to Hugging Face Space

on:
  push:
    branches: [ "main" ]   # change if your default branch differs
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      HF_USERNAME: janaka2                 # <-- your HF username/org
      HF_SPACE: RAG_Powerd_Chat_Bot        # <-- exact Space name (as in URL)

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Optional sanity: ensure the app file is present at repo root
      - name: Sanity check
        run: |
          echo "== Repo root =="
          ls -la
          test -f app.py || { echo "::error::app.py missing at repo root"; exit 1; }

      - name: Git identity & LFS
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git lfs install

      - name: Push to HF Space (HEAD -> main)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          set -e
          REMOTE="https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/${HF_USERNAME}/${HF_SPACE}"
          git remote add hf "$REMOTE" || git remote set-url hf "$REMOTE"
          git push --force hf HEAD:main
