name: Sync to Hugging Face Space

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      HF_USERNAME: janaka2
      HF_SPACE:    RAG_Powerd_Chat_Bot

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Sanity check files
        run: |
          ls -la
          test -f app.py || { echo "::error::app.py missing at repo root"; exit 1; }

      - name: Git identity & LFS
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git lfs install

      - name: Install HF CLI
        run: pip install --upgrade "huggingface_hub>=0.36.0"

      - name: Validate token & login (no token printed)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          set -e
          if [ -z "$HF_TOKEN" ]; then
            echo "::error::HF_TOKEN secret is missing"; exit 1
          fi
          # quick format sanity (length only; value stays masked)
          echo "HF_TOKEN length: ${#HF_TOKEN}"
          # Verify identity with new CLI (env var)
          HUGGINGFACE_HUB_TOKEN="$HF_TOKEN" hf auth whoami
          # Cache credentials for git
          echo "$HF_TOKEN" | hf auth login --stdin --add-to-git-credential

      - name: Push to HF Space (HEAD -> main)
        run: |
          set -e
          REMOTE="https://huggingface.co/spaces/${HF_USERNAME}/${HF_SPACE}"
          git remote add hf "$REMOTE" || git remote set-url hf "$REMOTE"
          git push --force hf HEAD:main
